site_name: 菲尼瑞斯资料下载中心

nav:
    - 数字示波器:
        - 数字示波器\双通道平板示波器 1013D.md
        - 数字示波器\二合一数字示波器 1014D.md
        - 数字示波器\50M双通道平板示波表 2C53P.md
        - 数字示波器\50M双通道示波器万用表 2C53T.md
        - 数字示波器\双通道示波器万用表 2C23T.md
        - 数字示波器\二合一数字荧光示波器 DPOX-180H.md
        - 数字示波器\三合一示波器 DSO-TC3.md
        - 数字示波器\手持示波器 1C15.md
        - 数字示波器\手持示波器 5012H.md
        - 数字示波器\手持示波器 FNIRSI-PRO.md
        - 数字示波器\迷你示波器 138PRO.md
        - 数字示波器\迷你数字示波器 DSO-510.md
        - 数字示波器\迷你数字示波器 DSO-152.md
        - 数字示波器\迷你数字示波器 DSO-153.md
    - 信号发生器:
        - 信号发生器\信号发生器 SG002A.md
        - 信号发生器\信号发生器 SG003A.md
        - 信号发生器\信号发生器 SG004A.md
    - 数字万用表:
        - 数字万用表\智能彩屏万用表 DMT-99.md
        - 数字万用表\大屏数显智能万用表 FNIRSI-S1.md
    - USB检测仪器: 
        - USB检测仪器/USB检测仪 FNIRSI-C1.md 
        - USB检测仪器/多接口USB检测仪 FNAC-28.md 
        - USB检测仪器/USB快充测试仪 FNB38.md 
        - USB检测仪器/USB快充测试仪 FNB48.md 
        - USB检测仪器/USB快充测速仪 FNB48P.md 
        - USB检测仪器/USB快充测试仪 FNB58.md 
    - 元器件检测仪器:
        - 元器件检测仪器/高精度内阻测试仪 HRM-10.md
        - 元器件检测仪器/晶体管检测仪 LCR-P1.md
        - 元器件检测仪器/智能电桥镊子 LCR-ST1.md
    - 智能焊接设备:
        - 智能焊接设备/精密智能焊台 DWS-200.md
        - 智能焊接设备/便携式智能彩屏点焊机 SWM-10.md
        - 智能焊接设备/智能电烙铁 HS-01.md
        - 智能焊接设备/智能电烙铁 HS-02.md
    - 环境监测仪器: 
        - 环境监测仪器/智能测糖仪 JBM-10 & 20.md
        - 环境监测仪器/感应式木材水分检测仪 WMT-10.md
        - 环境监测仪器/核辐射检测仪 CG-01.md
        - 环境监测仪器/数字噪音计 FDM-01.md
    - 家装测量仪器:
        - 家装测量仪器/墙体探测仪 WD-01.md
        - 家装测量仪器/墙体探测仪 WD-02.md
        - 家装测量仪器/智能测距仪 IR-40.md
    - 户外仪器仪表:
        - 户外仪器仪表/4K数码夜视仪 NVS-20.md
        - 户外仪器仪表/4K双目数码夜视仪 NVS-40.md
    - 汽修测量仪器: 
        - 汽修测量仪器/涂层测厚仪 CTG-20.md
    - 数控电源: 
        - 数控电源/便携式数控直流电源 DPS-150.md
    # - 其他仪器: 0.md

    # - 快速入门教程:
    #     - 0.md
    - 关于我们: 
        - 关于我们/公司简介.md
        - 关于我们/发展历史.md
        - 关于我们/联系方式.md
        - 关于我们/线上店铺.md

theme:
    name: "readthedocs"
